name: Deploy Deno Server to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Cache Deno modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/*.ts') }}
          restore-keys: |
            ${{ runner.os }}-deno

      - name: Build static files
        run: deno run start

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # The directory containing static content to be served by GitHub Pages

